# Generated by Django 4.0.2 on 2022-02-16 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 2, 16, 14, 25, 37, 835368))),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 14, 25, 37, 835368))),
            ],
        ),
    ]
